config/routes.rb
Rails.application.routes.draw do
  get 'savings/index'
  get 'savings/show'
  get 'savings/new'
  get 'savings/edit'
  get 'savings/create'
  get 'savings/update'
  get 'savings/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/dashboard", to: "pages#dashboard"
  get "/suggestions", to: "pages#suggestions"

  resources :accounts do
    resources :transactions
  end

  resources :savings do
    resources :transactions
  end

  resources :learning_materials do
    resources :quizzes
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <p class="footer-text">© Finlit, 2023.</p> %>

app/views/shared/_navbar.html.erb
<div class="nav-master">
  <%= link_to root_path class: "logo-div" do %>
    <img class="logo-finlit" title="Home" src="https://res.cloudinary.com/djr22sgp3/image/upload/v1678279740/Finlit_Logo_-_7_ghkx38.png">
  <% end %>
  <div class="navbar-finlit">
    <ul class="nav-elements" data-controller="navbar">
      <%= link_to "/", class: "nav-buttons", data: { navbar_target: "home" } do %><li class="nav-item"> 🏠 </li><% end%>
      <%= link_to dashboard_path, class: "nav-buttons", data: { navbar_target: "dashboard" } do %><li class="nav-item">Dashboard</li><% end%>
      <%= link_to accounts_path, class: "nav-buttons", data: { navbar_target: "accounts" } do %><li class="nav-item">Accounts</li><% end%>
      <%= link_to savings_path, class: "nav-buttons", data: { navbar_target: "savings" } do %><li class="nav-item">Savings</li><% end%>
      <%= link_to learning_materials_path, class: "nav-buttons", data: { navbar_target: "learningMaterial" } do %><li class="nav-item">Learning</li><% end%>
      <%= link_to suggestions_path, class: "nav-buttons", data: { navbar_target: "suggestion" } do %><li class="nav-item">Suggestions</li><% end%>
    </ul>
  </div>
  <div class="avatar-nav">
    <div class="avatar-location">
    <img class="avatar dropdown-toggle" class="avatar-reg" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://res.cloudinary.com/djr22sgp3/image/upload/v1678878773/peeps-avatar-3_oozbld.png" />
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
      <%= link_to "Accounts", accounts_path, class: "dropdown-item" %>
      <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
      <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
    </div>
  </div>
  <input type="checkbox" id="active">
    <label for="active" class="menu-btn"><i class="fas fa-bars"></i></label>
    <div class="wrapper">
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Gallery</a></li>
        <li><a href="#">Feedback</a></li>
      </ul>
    </div>
  </div>
</div>