config/routes.rb
Rails.application.routes.draw do
  get 'savings/index'
  get 'savings/show'
  get 'savings/new'
  get 'savings/edit'
  get 'savings/create'
  get 'savings/update'
  get 'savings/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/dashboard", to: "pages#dashboard"
  get "/suggestions", to: "pages#suggestions"

  resources :accounts do
    resources :transactions
  end

  resources :savings do
    resources :transactions
  end

  resources :learning_materials do
    resources :quizzes
  end
end

app/models/saving.rb
class Saving < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
  belongs_to :icon

  # validates :balance, numericality: { greater_than_or_equal_to: 0 }
  validates :balance, presence: true

  validates :balance, comparison: { less_than: :saving_goal,
    message: "saving goal should be less than your current balance." 
  }

  def self.saving_chart(account)
    balance = account.balance
    goal = account.saving_goal
    gap = goal - balance

    return {"savings" => balance, "lack" => gap}
  end

  def self.get_porcentage(account)
    return ((account.balance / account.saving_goal) * 100).round(2)
  end

  def updateBalance
    transactions = self.transactions
    transactions.each do |transaction|
      self.balance += transaction.amount
    end
  end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  before_action :set_saving, only: %i[ show edit update destroy ]
  before_action :set_balance, only: %i[ show edit update destroy ]

  def index
    @savings = Saving.where(user_id: current_user.id)

    @savings.each do |saving|
      saving.updateBalance
    end
  end

  def show
    if current_user.id == @saving.user_id
      @transactions = @saving.transactions
      
      @achive = (@saving.balance >= @saving.saving_goal)
    end
  end

  def new
    @saving = Saving.new
    # @account_type = ["Current account", "Saving", "Other"]
  end

  def edit
  end

  def create
    @saving = Saving.new(saving_params)
    icon_id = params[:saving][:icon_id]
    icon = icon_id.blank? ? (Icon.all).sample : Icon.find(icon_id)
    @saving.icon_id = icon.id
    @saving.user_id = current_user.id
   if @saving.save
    redirect_to savings_path
   else
    render :new, status: :unprocessable_entity
   end 
  end

  def update
    if current_user.id == @saving.user_id
      @saving.update(saving_params)

      redirect_to savings_path
    end
  end

  def destroy
    if current_user.id == @saving.user_id
      @saving.destroy
    end

    redirect_to savings_path, status: :see_other
  end

  private

  def set_saving
    @saving = Saving.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def saving_params
    params.require(:saving).permit(:saving_name, :saving_goal, :balance, :user_id, :time_goal, :icon_id)
  end

  def set_balance
    @saving = Saving.find(params[:id])
    @saving.updateBalance
  end
end

app/views/savings/_form.html.erb
<div>
    <%= simple_form_for @saving do |f| %>
    <div class="form-inputs">
        <%= f.input :saving_name %>
<<<<<<< HEAD
        <%= f.input :balance %>
        <%=  f.input :saving_goal %>
        <%= f.input :time_goal, as: :date %>
        <%= f.association :icon,
                        as: :radio_buttons,
                        collection: Icon.all.map { |icon| [".", " ", style: "background-image: url(#{cl_image_path(icon.url)});"] },
=======
        <%= f.input :balance, label: "Current Balance"%>
        <%= f.input :saving_goal %>
        <%= f.input :time_goal, as: :date %>
        <%= f.association :icon,
                        as: :radio_buttons,
                        collection: Icon.all.map { |icon| [".", icon.id, style: "background-image: url(#{cl_image_path(icon.url)});"] },
>>>>>>> main
                        input_html: {
                        class: "icon-radio"
                        }
        %>
    </div>
    <div class="form-actions">
        <%= f.button :submit %>
    </div>
    <% end %>

</div>

app/views/savings/_saving.html.erb
<div id="<%= dom_id saving %>">
  <% if @achive %>
    <div class="intro-savings-card-show">
      <div class="intro-savings-card">
        <%= cl_image_tag Icon.find(saving.icon_id).url, class:"bank-avatar-savings"%>
        <p class="savings-card-p"><strong>Saving:</strong><br><%= saving.saving_name %></p>
      </div>
    </div>
    <div>
<<<<<<< HEAD
    <p>Balance: <%= "£#{number_with_precision(saving.balance, precision: 2, delimiter: ',')}" %></p>
    <p><strong>Your already achieve your saving goal, congrats! 🤑🍾</strong></p>
=======
      <p>Balance: <%= "£#{number_with_delimiter(saving.balance, :delimiter => ',')}" %></p>
      <p><strong>Your already achieved your saving goal, congrats! 🤑🍾</strong></p>
>>>>>>> main
    </div>
  <% else %>
    <div class="intro-savings-card-show">
      <div class="intro-savings-card">
        <%= cl_image_tag Icon.find(saving.icon_id).url, class:"bank-avatar-savings"%>
        <p class="savings-card-p"><strong>Saving:</strong><br><%= saving.saving_name %></p>
      </div>
    </div>
    <div>
      <p>Balance: <%= "£#{number_with_precision(saving.balance, precision: 2, delimiter: ',')}" %></p>
      <p>Goal: <%= "£#{number_with_precision(saving.saving_goal, precision: 2, delimiter: ',')}" %></p>
      <p>Saved: <%= Saving.get_porcentage(saving) %>%</p>
    </div>
  <% end %>
</div>

app/views/savings/_savings_card.html.erb
<%= link_to saving, class:"savings-grid-item" do%>
  <div class="intro-savings-card">
      <%= cl_image_tag Icon.find(saving.icon_id).url, class:"bank-avatar-accounts"%>
      <p class="savings-card-p"><strong>Savings:</strong><br><%= saving.saving_name %></p>
  </div>
  <div class="savings-card-data">
    <div id="savings-card-data-chart">
      <%= pie_chart Saving.saving_chart(saving), donut: true, height: '100px', width: '100px', legend: false, colors: ["#794CF0", "#4C4B4E"], library: {animation: {easing: 'easeOutQuad'}, elements: {arc: {borderWidth: 0}}, plotOptions: { pie: { dataLabels: { enabled: false }}} } %>
    </div>
    <p>Saved<br><span class="account-card-balance"><%= Saving.get_porcentage(saving) %>%</span></p>
  </div>
  <div class="savings-card-data">
    <div class="savings-message-card">
      <% saving.updateBalance %>
      <p>You've saved <span class="motivational-message-span"><%= "£#{number_with_precision(saving.balance, precision: 2, delimiter: ',')}" %></span><br>Keep it up 🙌</p>
    </div>
  </div>
<% end %>

app/views/savings/edit.html.erb
<div class="log-in-master">
  <div class="log-in-container">
      <h2>Edit saving</h2>
      <%= render "form", saving: @saving %>
  </div>
</div>

app/views/savings/index.html.erb
<%# <p style="color: green"><%= notice %></p> %>
<div class="background-gradient-master-accounts">
  <div class="background-gradient-container-accounts"></div>
  <div class="shadow-gradient"></div>
</div>
    <div data-controller="select-accounts">
      <div class="accounts-menu">
        <div class="accounts-title-row">
          <div>
            <%= form_with url: accounts_path, method: :get, class: "d-flex" do %>
              <%= select_tag :query,
                options_for_select([["Savings", "Savings"], ["Accounts", "Accounts"]]),
                data: { select_accounts_target: "switch", action: "change->select-accounts#displayAccounts" },
                class: "account-switcher"
              %>
              <%= submit_tag "Filter", class: "btn btn-primary", data: { select_accounts_target: "btn" }%>
            <% end %>
          </div>
        </div>
        <div class="add-btn-flex">
          <%= button_to "+", new_saving_path, :class => "add-btn", :title => "Add a Saving >", :method => :get %>
        </div>
      </div>
      <div id="accounts">
        <div class="account-grid-container" data-select-accounts-target="grid">
          <% if @savings.length <= 0 %>
            <div class = "savings-grid-item">
              <%= link_to new_saving_path, class: "account-link" do %>
                <div class="intro-accounts-card">
                    <p>Let's create a new <strong>Saving!</strong></p>
                </div>
                <p>Create a saving and achive you goals! 🤑</p>
                <%= button_to "Create!", new_account_path, class:"card-action-buttons",  :method => :get %>
              <% end %>
            </div>
          <% else %>
            <% @savings.each do |saving| %>
              <div class="savings-card">
                <div class="acc-btn-flex">
                  <%# ---------- %>
                  <div class="btn-pluss-master">
                    <nav class="btn-pluss-wrapper-accounts">
                      <div href="#" class="btn-pluss-accounts">
                        <ul>
                          <li><%= link_to "✏️  |  Edit", edit_saving_path(saving) %></li>
                          <li><%= link_to "🗑️  |  Delete", saving_path(saving), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
                        </ul>
                      </div>
                    </nav>
                  </div>
                <%# ---------- %>
                </div>
                <%= render "savings_card", saving: saving %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/savings/new.html.erb
<div class="log-in-master">
  <div class="new-saving-container">
      <h2 class="saving-title">New Saving</h2>
      <br>
      <br>
      <%= render "form", saving: @saving %>
  </div>
  <%= link_to "< Back to Accounts", savings_path, class: "back-account-btn" %>
</div>

app/views/savings/show.html.erb
<div class="background-gradient-master-transactions">
  <div class="background-gradient-container-transactions"></div>
  <div class="shadow-gradient"></div>
</div>
<h1 class="transactions-title">Saving - <%= @saving.saving_name%> </h1>
<div class="account-flex">
  <div class="account-grid-item-transaction">
    <div class="return-btn-flex">
       <%= button_to "<", savings_path, class:"return-btn",  :method => :get %>
    </div>
    <%= render @saving %>
    <div>
      <%# ------------ %>
      <div class="btn-pluss-master">
        <nav class="btn-pluss-wrapper">
          <div href="#" class="btn-pluss">
            <ul>
              <li><%= link_to "✏️  |  Edit", edit_saving_path(@saving) %></li>
              <li><%= link_to "🗑️  |  Delete", saving_path(@saving), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
            </ul>
          </div>
        </nav>
      </div>
      <%# ---------- %>
    </div>
  </div>
  <div class="graph-pie">
    <%= pie_chart Saving.saving_chart(@saving), donut: true, height: '400px', width: '300px', colors: ["#794CF0", "#4C4B4E"], library: {animation: {easing: 'easeOutQuad'}, elements: {arc: {borderWidth: 0}}, plotOptions: { pie: { dataLabels: { enabled: false }}} } %>
  </div>
  <%# <p id="saved-title-show">Saved<br>£<span class="account-card-balance"><%= Account.get_porcentage(@account) %>
</div>
  <%# ----------- SCROLLER ANIMATION ------------ %>
<div class="scroller-wheel">
  <a href="javascript:;" class="scroll-down mouse effect1">
    <span id="scroll-down-span"></span>
  </a>
</div>
<p id="scroll-p">View Transactions</p>
<div class="container-scroll">
  <div id="typewriter-output"></div>
  <span id="cursor"></span>
</div>
<script>
  setTimeout(function() {
    document.getElementById("scroll-p").style.display = "block";
    document.getElementById("scroll-p").style.opacity = 0;

    setTimeout(function() {
      document.getElementById("scroll-p").style.transition = "opacity 3s ease-in";
      document.getElementById("scroll-p").style.opacity = 1;
    }, 10);
  }, 2000);
  setTimeout(function() {
    document.querySelector(".scroller-wheel").style.display = "block";
    document.querySelector(".scroller-wheel").style.opacity = 0;

    setTimeout(function() {
      document.querySelector(".scroller-wheel").style.transition = "opacity 3s ease-in";
      document.querySelector(".scroller-wheel").style.opacity = 1;
    }, 10);
  }, 1000);
</script>
<%# ----------- SCROLLER ANIMATION END ------------ %>
<div class="background-gradient-master-transactions">
  <div class="background-gradient-container-transactions-bottom"></div>
</div>
<h1 class="transactions-title-lower">Records</h1>
<div class="transactions-master">
  <div class="transactions-location-div">
    <% @transactions.each do |transaction| %>
      <div class="transaction-btn-flex">
      <%# ---------- %>
      <div class="btn-pluss-transactions-master">
        <div class="btn-pluss-wrapper-transactions">
          <div href="#" class="btn-pluss-transactions">
            <ul>
              <li><%= link_to "✏️  |  edit", edit_saving_transaction_path(@saving, transaction) %></li>
              <li><%= link_to "🗑️  |  Delete", saving_transaction_path(@saving, transaction), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
            </ul>
          </div>
        </div>
      </div>
      <%# ---------- %>
      </div>
      <div class="transactions-list-master">
        <div class="transactions-card">
          <%= cl_image_tag Icon.find(@saving.icon_id).url, class:"bank-avatar-transaction"%>
          <%= render partial: 'transactions/record', locals: { transactions: transaction } %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <div class="record-btn-flex">
    <%= button_to "+", new_saving_transaction_path(@saving), class: "add-btn", title: "Add Record", method: :get %>
  </div>
</div>