config/routes.rb
Rails.application.routes.draw do
  get 'savings/index'
  get 'savings/show'
  get 'savings/new'
  get 'savings/edit'
  get 'savings/create'
  get 'savings/update'
  get 'savings/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/dashboard", to: "pages#dashboard"
  get "/suggestions", to: "pages#suggestions"

  resources :accounts do
    resources :transactions
  end

  resources :savings do
    resources :transactions
  end

  resources :learning_materials do
    resources :quizzes
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  CATEGORIES = ['Groceries', 'Transportation', 'Entertainment', 'Utilities', 'Other']
  before_action :set_transaction, only: %i[ show edit update destroy ]
  before_action :set_type_account, only: %i[ new edit create update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = @account.transactions.new
    @user_accounts = Account.where(user_id: current_user.id)
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    
    if params[:account_id].nil?
      @transaction = Transaction.new(transaction_params)
      @transaction.saving = @account
      # @transaction.save

      if @transaction.save
        redirect_to saving_path(@account.id)
       else
        render :new, status: :unprocessable_entity
       end
      # redirect_to saving_path(@account.id)
    else
      @transaction = Transaction.new(transaction_params)
      @transaction.account = @account
      # @transaction.save

      if @transaction.save
        redirect_to account_path(@account.id)
       else
        render :new, status: :unprocessable_entity
       end
      # redirect_to account_path(@account.id)
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    @transaction.update(transaction_params)

    if @account.class == Saving
      # @account = Saving.find(params[:account_id])
      redirect_to saving_path(@account)
    else
      # @account = Account.find(params[:account_id])
      redirect_to account_path(@account)
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
  
    if @account.class == Saving
      # @account = Saving.find(params[:account_id])
      redirect_to saving_path(@account), status: :see_other
    else
      # @account = Account.find(params[:account_id])
      redirect_to account_path(@account), status: :see_other
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:operation_type, :category, :amount, :date)
    end

    # def transaction_params_saving
    #   params.require(:transaction).permit(:operation_type, :amount, :date)
    # end

    def set_type_account
      if params[:account_id].nil?
        @account = Saving.find(params[:saving_id])
      else
        @account = Account.find(params[:account_id])
      end
    end
end

app/views/transactions/_account_form.html.erb
<div>
  <%= link_to "< Back to Accounts", account_path(@account), class: "back-account-btn" %>
</div>
<%= simple_form_for [@account, @transaction] do |f| %>
  <%= f.input :operation_type, input_html: { data: {set_amount_target: "typeInput"} } %>
  <%= f.input :category, collection: [" "], prompt: "Select a category", input_html: { data: { set_amount_target: "category" }}%>
  <%= f.input :amount, as: :decimal, input_html: { data: { set_amount_target: "amountInput", action: "input->set-amount#amountChanging" }} %>
  <%= f.input :date, as: :date %>
  <div class="form-actions" >
    <%= f.button :submit, value: "Create", class: "add-btn-new-transactions", data: {
                  set_amount_target: "buttonCreate",
                  action: "mouseenter->set-amount#buttonHover mouseleave->set-amount#buttonMouseLeft"
                } %>
  </div>
<% end %>

app/views/transactions/_accounts.html.erb
# Display all the user accounts with the current balance of each one.
# could set the amount of the user want to pass between the account and the saving.
# Update the accont current balance.

<h1>Display accounts</h1>
<div class="record-accounts-grid">
  <% accounts.each do |account| %>
    <div class="record-accounts-card">
      <p><strong>Name:</strong> <%= account.account_name %></p>
      <p><strong>Type:</strong> <%= account.account_type%></p>
      <input type="range" min="0" max="<%= account.balance %>" value="0">
    </div>
  <% end %>
</div>

app/views/transactions/_add_saving_form.html.erb
<div>
  <%= link_to "< Back to Accounts", savings_path, class: "back-account-btn" %>
</div>
<%= simple_form_for [account, transaction] do |f| %>
  <%= f.input :operation_type, input_html: { data: {set_amount_target: "typeInput"} } %>
  <%= f.input :amount, as: :decimal, input_html: { data: { set_amount_target: "amountInput", action: "input->set-amount#amountChanging" }}  %>
  <%= f.input :date, as: :date %>
  <div class="form-actions">
    <%= f.button :submit, value: "Add", data: {
                  set_amount_target: "buttonCreate",
                  action: "mouseenter->set-amount#buttonHover mouseleave->set-amount#buttonMouseLeft"
                } %>
  </div>
<% end %>

app/views/transactions/_edit_account.html.erb
<div class="log-in-master">
  <div class="log-in-container">
    <h2>Edit Transaction</h2>
    <div data-controller="account-card">
      <%= simple_form_for [@account, @transaction] do |f| %>

        <div class="form-inputs">
          <%= f.input :operation_type, collection: ["Income", "Expense"], prompt: "Select an operation" %>
          <%= f.input :category, collection: Transaction.categories, prompt: "Select a category" %>
          <%= f.input :amount, as: :decimal, input_html: { data: { set_amount_target: "amountInput"}} %>
          <%= f.input :date, as: :date %> 
        </div>
        <div class="form-actions">
          <%= f.button :submit, value: "Update", class: "add-btn-new-transactions" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/_edit_saving.html.erb
<div data-controller="account-card">
  <%= simple_form_for [@account, @transaction] do |f| %>
  <%= f.input :operation_type, input_html: { data: {set_amount_target: "typeInput"} } %>
  <%= f.input :amount, as: :decimal, input_html: { data: { set_amount_target: "amountInput", action: "input->set-amount#amountChanging" }}  %>
  <%= f.input :date, as: :date %>
  <div class="form-actions">
    <%= f.button :submit, value: "Add", data: {
                  set_amount_target: "buttonCreate",
                  action: "mouseenter->set-amount#buttonHover mouseleave->set-amount#buttonMouseLeft"
                } %>
  </div>
<% end %>
</div>

app/views/transactions/_form.html.erb
<div class="log-in-master">
  <div class="log-in-container">
    <h2>Edit Acount</h2>
    <div data-controller="account-card">
      <%= simple_form_for [@account, @transaction] do |f| %>

        <div class="form-inputs">
          <%= f.input :category %>
          <%= f.input :amount %>
          <%= f.input :date %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, value: "Update" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/_record.html.erb
<div id="<%= dom_id transactions %>">
  <ul class="transactions-list-data">
    <li><strong>Date:</strong><br><%= transactions.date %><li>
    <% if transactions.operation_type == "income" %>
      <li><h5><span class="transactions-price-green"><%= "£#{number_with_precision(transactions.amount, precision: 2, delimiter: ',')}" %></span></h5><li>
    <% else %>
      <li><h5><span class="transactions-price-red"><%= "£#{number_with_precision(transactions.amount, precision: 2, delimiter: ',')}" %></span></h5><li>
    <% end %>
  </ul>
</div>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transactions %>">
    <ul class="transactions-list-data">
      <li class="transactions-category-master"><strong>Category:</strong><br><%= transactions.category %><li>
      <li class="transactions-date-master"><strong>Date:</strong><br><%= transactions.date %><li>
      <% if transactions.operation_type == "income" %>
        <li class="transactions-price-master"><h5><span class="transactions-price-green"><%= "£#{number_with_precision(transactions.amount, precision: 2, delimiter: ',')}" %></span></h5><li>
      <% else %>
        <li class="transactions-price-master"><h5><span class="transactions-price-red"><%= "£#{number_with_precision(transactions.amount, precision: 2, delimiter: ',')}" %></span></h5><li>
      <% end %>
    </ul>
</div>

app/views/transactions/edit.html.erb
<div class="log-in-master">
  <div  data-controller="set-amount" class="create-account-container" data-set-amount-target="card">
    <% if @account.class == Saving %>
      <h1 class="title-text">Edit Saving Record</h1>
    <% else %>
      <h1 class="title-text">Edit Account Transaction</h1> 
    <% end %>

    <div class="switch-button-transaction">
      <div class="switch-option" data-set-amount-target="switchButtons"> 
        <input type="radio" name="switch-option" id="income-option" checked>
        <label class="option-label-transaction-income" for="income-option" data-action="click->set-amount#setIncome">Income</label>
        <input type="radio" name="switch-option" id="expense-option">
        <label class="option-label-transaction-expense" for="expense-option" data-action="click->set-amount#setExpense">Expense</label>
      </div>
    </div>

    <% if @transaction.account_id == nil %>
      <%= render "edit_saving", account: @account, transaction: @transaction %>
    <% else %>
      <%# <%= render "edit_account", transaction: @transaction %>
      <%= render "account_form", account: @account, transaction: @transaction %>
    <% end %>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="log-in-master" data-controller="set-amount">
  <div class="create-account-container" data-set-amount-target="card">
    <% if @account.class == Saving %>
      <h1 class="title-text">New Record</h1>
    <% else %>
      <h1 class="title-text">New Transaction</h1> 
    <% end %>

    <div class="switch-button-transaction">
      <div class="switch-option" data-set-amount-target="switchButtons"> 
        <input type="radio" name="switch-option" id="income-option" checked>
        <label class="option-label-transaction-income" for="income-option" data-action="click->set-amount#setIncome">Income</label>
        <input type="radio" name="switch-option" id="expense-option">
        <label class="option-label-transaction-expense" for="expense-option" data-action="click->set-amount#setExpense">Expense</label>
      </div>
    </div>

    <% if @account.class == Saving %>
      <%= render "add_saving_form", account: @account, transaction: @transaction %>
    <% else %>
      <%= render "account_form", account: @account, transaction: @transaction %>
    <% end %>
  </div>

  <% if @account.class == Saving %>
    <%= render "accounts", accounts: @user_accounts %>
  <% end %>
</div>

app/views/transactions/show.html.erb
<%# <p style="color: green"><%= notice %></p> %>

<% if @transaction.account_id == nil %>

<% else %>
    <%= render @transaction %>
<% end %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Remove Transaction", @transaction, method: :delete %>
</div>