config/routes.rb
Rails.application.routes.draw do
  get 'savings/index'
  get 'savings/show'
  get 'savings/new'
  get 'savings/edit'
  get 'savings/create'
  get 'savings/update'
  get 'savings/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/dashboard", to: "pages#dashboard"
  get "/suggestions", to: "pages#suggestions"

  resources :accounts do
    resources :transactions
  end

  resources :savings do
    resources :transactions
  end

  resources :learning_materials do
    resources :quizzes
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  belongs_to :icon
  has_many :transactions, dependent: :destroy

  # validates :balance, numericality: { greater_than_or_equal_to: 0 }
  validates :balance, presence: true

  def updateBalance
    transactions = self.transactions
    transactions.each do |transaction|
      self.balance += transaction.amount
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :set_balance, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @selected_option = params[:query]
    # user_account = current_user.id
    @selected_option = "Accounts" if @selected_option == nil

    user_accounts = Account.where(user_id: current_user.id)
    @accounts = user_accounts.all

    if params[:query] == "Accounts"
      @accounts = user_accounts.all
      redirect_to controller: :accounts, action: :index 
    elsif params[:query] == "Savings"
      redirect_to controller: :savings, action: :index  
    end
  end

  # GET /accounts/1 or /accounts/1.json
  def show
    if current_user.id == @account.user_id
      @transactions = @account.transactions
    end
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @account_type = ["Current account", "Saving", "Other"]
  end

  # GET /accounts/1/edit
  def edit
    # @account = Account.find(params[:id])
  end

  # POST /accounts or /accounts.json
  def create
    # raise
    @account = Account.new(account_params)
    icon_id = params[:account][:icon_id]
    icon = icon_id.blank? ? (Icon.all).sample : Icon.find(icon_id)
    @account.icon_id = icon.id
    @account.user_id = current_user.id
    @account.save

    redirect_to accounts_path
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    # account = Account.find(params[:id])
    if current_user.id == @account.user_id
      @account.update(account_params)

      redirect_to accounts_path
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    if current_user.id == @account.user_id
      @account.destroy
    end

    redirect_to accounts_path, status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:account_name, :account_type, :balance, :user_id, :account_number, :icon_id)
    end

    def set_balance
      @account = Account.find(params[:id])
      @account.updateBalance
    end
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p data-select-accounts-target="type">
    <strong>Type:</strong> <%= account.account_type %>
  </p>
  <p data-select-accounts-target="type">
    <strong>Name:</strong> <%= account.account_name %>
  </p>
  <p data-select-accounts-target="type">
    <strong>Number:</strong> <%= account.account_number %>
  </p>
  <p data-select-accounts-target="type">
    <strong>Balance:</strong> <%= "£#{number_with_precision(account.balance, precision: 2, delimiter: ',')}" %>
  </p>
</div>

app/views/accounts/_accounts_card.html.erb
<div class = "account-grid-item">
  <%= link_to account, class: "account-link" do %>
    <div class="intro-accounts-card">
        <%= cl_image_tag Icon.find(account.icon_id).url, class:"bank-avatar-accounts"%>
        <%# <img class="bank-avatar-accounts" src="https://res.cloudinary.com/djr22sgp3/image/upload/v1678225833/Full_Black_BG-W-P0.05_zyr5xs.png"/> %>
        <p><strong>Account:</strong> <%= account.account_name %></p>
        <p><strong>Type:</strong> <%= account.account_type %></p>
    </div>
    <% account.updateBalance %>
    <p>Balance<br><span class="account-card-balance"><%= "£#{number_with_precision(account.balance, precision: 2, delimiter: ',')}" %></span></p>
  <% end %>
  <%= button_to "+ Add", new_account_transaction_path(account), class:"card-action-buttons",  :method => :get %>
</div>

app/views/accounts/_form.html.erb
<div class="log-in-master">
  <div class="create-account-container" data-controller="account-card">
    <div class="add-account-bank-avatar-master">
      <% %>
      <%# <%= cl_image_tag Icon.all.first.url, class:"add-account-bank-avatar"%>
      <%# <button class="modify-btn" title="Update Account Picture" data-account-card-target="iconButton" data-action="click->account-card#changeIcon">+</button> %>
    </div>
    <h2 class="add-account-h2">Add an Account</h2>
    <br>
    <div>
      <%= simple_form_for [@account], data: { account_card_target: "form" } do |f| %>
        <div class="form-inputs">
          <%= f.input :account_name %>
          <%= f.input :account_type,
                      collection: ['Current account', 'Cash', 'Credit card', 'Investment'],
                      prompt: "Select a type" %>
          <%= f.input :balance %>
          <%= f.input :account_number  %>
        </div>
        <%= f.association :icon,
                        as: :radio_buttons,
                        collection: Icon.all.map { |icon| [str="'", icon.id, { style: "background-image: url(#{cl_image_path(icon.url, :crop => :fill, :width => 50, :height => 50, :gravity => :auto)}); object-fit: cover; width: 50px; height: 50px;" }] },
                        input_html: {
                        class: "icon-radio"
                        }
        %>
        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/accounts/edit.html.erb
<div class="log-in-master">
  <div class="log-in-container">
    <h2>Edit Account</h2>
    <div data-controller="account-card">
      <%= simple_form_for @account, data: { account_card_target: "form" } do |f| %>
        <div class="form-inputs">
          <%= f.input :account_name %>
          <%= f.input :account_type,
                      collection: ['Current account', 'Cash', 'Credit card', 'Investment'],
                      prompt: "Select a type",
                      input_html: { data: { account_card_target: 'input', action: "change->account-card#accountType" } } %>
          <%= f.input :balance %>
          <%= f.input :account_number %>
        </div>
        <%= f.association :icon,
                        as: :radio_buttons,
                        collection: Icon.all.map { |icon| [".", icon.id, style: "background-image: url(#{cl_image_path(icon.url)});"] },
                        input_html: {
                        class: "icon-radio"
                        }
        %>
        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<div class="background-gradient-master-accounts">
  <div class="background-gradient-container-accounts"></div>
  <div class="shadow-gradient"></div>
</div>
    <div data-controller="select-accounts">
      <div class="accounts-menu">
        <div class="accounts-title-row">
          <div>
            <%= form_with url: accounts_path, method: :get, class: "d-flex" do %>
              <%= select_tag :query,
                options_for_select([["Accounts", "Accounts"], ["Savings", "Savings"]]),
                data: { select_accounts_target: "switch", action: "change->select-accounts#displayAccounts" },
                class: "account-switcher"
              %>
              <%= submit_tag "Filter", class: "btn btn-primary", data: { select_accounts_target: "btn" }%>
            <% end %>
          </div>
        </div>
        <div class="add-btn-flex">
          <%= button_to "+", new_account_path, :class => "add-btn", :title => "Add an Account >", :method => :get %>
        </div>
      </div>
      <div id="accounts">
        <div class="account-grid-container" data-select-accounts-target="grid">
          <% if @accounts.length <= 0 %>
            <div class = "account-grid-item">
              <%= link_to new_account_path, class: "account-link" do %>
                <div class="intro-accounts-card">
                    <h4>Let's create a new <strong>Account!</strong></h4>
                    <h6>Create an account an track your money 🤯</h6>
                </div>
                <%= button_to "Create!", new_account_path, class:"card-action-buttons",  :method => :get %>
              <% end %>
            </div>
          <% else %>
            <% @accounts.each do |account| %>
              <div class="account-card">
                <div class="acc-btn-flex">
                  <%# ---------- %>
                  <div class="btn-pluss-master">
                    <nav class="btn-pluss-wrapper-accounts">
                      <div href="#" class="btn-pluss-accounts">
                        <ul>
                          <li><%= link_to "✏️  |  Edit", edit_account_path(account) %></li>
                          <li><%= link_to "🗑️  |  Delete", account_path(account), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
                        </ul>
                      </div>
                    </nav>
                  </div>
                <%# ---------- %>
                </div>
                  <%= render "accounts_card", account: account %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "< Back to Accounts", accounts_path, class: "back-account-btn" %>
</div>

app/views/accounts/show.html.erb
<div class="background-gradient-master-transactions">
  <div class="background-gradient-container-transactions"></div>
  <div class="shadow-gradient"></div>
</div>
<h1 class="transactions-title">Account</h1>
<div class="account-flex">
  <div class="account-grid-item-transaction">
    <div class="return-btn-flex">
      <%= button_to "<", root_path, class:"return-btn",  :method => :get %>
    </div>
    <%= cl_image_tag Icon.find(@account.icon_id).url, class:"bank-avatar"%>
    <%= render @account %>
    <div>
      <%# ------------ %>
      <div class="btn-pluss-master">
        <nav class="btn-pluss-wrapper">
          <div href="#" class="btn-pluss">
            <ul>
              <li><%= link_to "✏️  |  Edit", edit_account_path(@account) %></li>
              <li><%= link_to "🗑️  |  Delete", account_path(@account), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
            </ul>
          </div>
        </nav>
      </div>
      <%# ---------- %>
    </div>
  </div>
  <div class="graph-img">
    <%= line_chart Transaction.line_chart(@account), colors: ["#6610f2"]  %>
  </div>
</div>
<%# ----------- SCROLLER ANIMATION ------------ %>
<div class="scroller-wheel">
  <a href="javascript:;" class="scroll-down mouse effect1">
    <span id="scroll-down-span"></span>
  </a>
</div>
<p id="scroll-p">View Transactions</p>
<div class="container-scroll">
  <div id="typewriter-output"></div>
  <span id="cursor"></span>
</div>
<script>
  setTimeout(function() {
    document.getElementById("scroll-p").style.display = "block";
    document.getElementById("scroll-p").style.opacity = 0;

    setTimeout(function() {
      document.getElementById("scroll-p").style.transition = "opacity 3s ease-in";
      document.getElementById("scroll-p").style.opacity = 1;
    }, 10);
  }, 2000);
  setTimeout(function() {
    document.querySelector(".scroller-wheel").style.display = "block";
    document.querySelector(".scroller-wheel").style.opacity = 0;

    setTimeout(function() {
      document.querySelector(".scroller-wheel").style.transition = "opacity 3s ease-in";
      document.querySelector(".scroller-wheel").style.opacity = 1;
    }, 10);
  }, 1000);
</script>
<%# ----------- SCROLLER ANIMATION END ------------ %>
<div class="background-gradient-master-transactions-bottom">
  <div class="background-gradient-container-transactions-bottom"></div>
</div>
<h1 class="transactions-title-lower">Transactions</h1>
<div class="transactions-master">
  <div class="transactions-location-div">
    <% @transactions.each do |transaction| %>
      <div class="transaction-btn-flex">
      <%# ---------- %>
      <div class="btn-pluss-transactions-master">
        <div class="btn-pluss-wrapper-transactions">
          <div href="#" class="btn-pluss-transactions">
            <ul>
              <li><%= link_to "✏️  |  edit", edit_account_transaction_path(@account, transaction) %></li>
              <li><%= link_to "🗑️  |  Delete", account_transaction_path(@account, transaction), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
            </ul>
          </div>
        </div>
      </div>
      <%# ---------- %>
      </div>
      <div class="transactions-list-master">
        <div class="transactions-card">
          <%= cl_image_tag Icon.find(@account.icon_id).url, class:"bank-avatar-transaction"%>
          <%= render partial: 'transactions/transaction', locals: { transactions: transaction } %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <%# <%= button_to "+ Add", new_account_transaction_path(@account), class:"card-action-buttons",  :method => :get %>
  <div class="record-btn-flex">
    <%= button_to "+", new_account_transaction_path(@account), class: "add-btn", title: "Add Transactions", method: :get %>
  </div>
</div>